# Generated by Django 4.1.2 on 2022-10-20 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_remove_blog_category_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='completes',
            field=models.ManyToManyField(blank=True, related_name='user_completes', to=settings.AUTH_USER_MODEL),
        ),
    ]
