# Generated by Django 4.1.2 on 2022-10-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_completes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
